### ISSUE TITLE
limit of 119 frames?

### ISSUE THREAD

**Issue by WithFeelingOfficial** [rewbs/sd-parseq#84] opened 2023-05-14 08:38 UTC
I cant seem to make something longer than 119? is it limited?

**Comment by daclaro** [comment] 2023-05-14 09:39
me too looking for answers here

**Comment by rewbs** [comment] 2023-05-14 11:05
No, it is not limited to 119 frames. That is just the default final frame positon.

To make a longer animation simply add another frame with a higher frame number, or edit the final frame number and set it to a higher value.

**Comment by WithFeelingOfficial** [comment] 2023-05-14 15:24
Hey! I managed to do it by copy and pasting your blank settings and changing the frame in those first, I can’t for the life of me see where to do it otherwise, I can’t see where the final frame amount is, a screen shot would be great!Thanks! Wonderful program btw! Chris Atkins Co-Founder, Managing Director +971 (0)55 148 2259 WithFeeling.com On 14 May 2023, at 15:06, Robin Fernandes ***@***.***> wrote:﻿
No, it is not limited to 119 frames. That is just the default final frame positon.
To make a longer animation simply add another frame with a higher frame number, or edit the final frame number and set it to a higher value.

**Comment by daclaro** [comment] 2023-05-14 16:54
its glitched I think when you add another frame for example 150 and click outside it brings you back to 120 frames

**Comment by alcool91** [comment] 2023-05-22 14:31
![image](https://github.com/rewbs/sd-parseq/assets/7366322/ca19a1e2-bef2-483f-9908-513a183c802d)

Hey! I was confused by this same issue which is why I came here, here is how I think you need to solve it. In the keyframes section you need to add a keyframe at a position higher than 120, _then and only then_  can you make prompts for the higher frame numbers. Your maximum frame is the highest keyframe, as far as I can tell. Please do correct me if I'm wrong, but this worked for me to generate frames past 120.

**Comment by rewbs** [comment] 2023-05-22 17:01
That's right, you can add a keyframe or edit the position of the final keyframe.

Keyframes are the core construct of parseq. The last keyframe defines the final frame of the animation. 

I'm going to close this issue because everything is working as intended. I will think about how to make this more intuitive.

**Closed** 2023-05-22 17:02 UTC
