### ISSUE TITLE
Why is there a lot of noise？

### ISSUE THREAD

**Issue by wuyue0509** [rewbs/sd-parseq#150] opened 2023-06-21 02:00 UTC
![image](https://github.com/rewbs/sd-parseq/assets/124325018/5b8e21db-612f-4648-8010-6a50c0011f5b)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/eea47ef7-0a90-41c5-a022-bb21e26d6991)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/f7bc89f6-8e58-4060-b5bd-db568f3855f2)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/e5a324ff-1d8c-43fb-859f-1550bd3f0e81)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/cfb6e115-7b73-411b-83f8-1a634ea9a02d)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/5e5b0d31-0352-42aa-85a0-f5585be55bf3)
![image](https://github.com/rewbs/sd-parseq/assets/124325018/e2bf0fb2-3c3d-469e-846f-60c3f0ea8cef)
I just adjusted the parameters normally as before, but now except for the first frame of the picture, other frames start to appear noise. Is there a step I made a mistake?

**Comment by rewbs** [comment] 2023-06-21 13:26
> I just adjusted the parameters normally as before

Do you mean you have a prior video in which you did not have the noise problem? If so could you attach the deforum output settings.txt files for both runs so I can compare them?

Alternatively, it may just be because the strength is too high. Could you try lowering to 0.65 instead of 0.8 (of course you'll get worse consistency but I'd like to see if it helps the "noise".

Lastly, what are your coherence settings? Any colour correction or optical flow?

**Comment by wuyue0509** [comment] 2023-06-22 03:27
I have returned the version of deforum to the previous version, the same parameter configuration, strength: 0.8, there is no noise problem at present, I think it may be the problem of the new version of deforum.

**Comment by rewbs** [comment] 2023-06-22 03:47
Good job for figuring that out. I will close this ticket because it doesn't sound related to Parseq.

As a sidenote: often this kind of "regression" between versions of Deforum is simply because some parameter's default value has changed. I recommend diffing the settings.txt from a good and bad run to see if there's a simple explanation. This way you don't have to stay stuck on an old version.

**Closed by rewbs** 2023-06-22 03:47 UTC
